run <- function(char1 = "",
               char2 = "",
               char3 = "",
               char4 = "",
               char5 = "",
               char6 = "",
               char7 = "",
               char8 = "",
               char9 = "",
               char10 = "",
               char11 = "",
               char12 = "",
               char13 = "",
               char14 = "",
               char15 = "",
               char16 = "",
               char17 = "",
               char18 = "",
               char19 = "",
               char20 = "",
               global = TRUE){
  if(global){
    char = paste(
      char1,
      char2,
      char3,
      char4,
      char5,
      char6,
      char7,
      char8,
      char9,
      char10,
      char11,
      char12,
      char13,
      char14,
      char15,
      char16,
      char17,
      char18,
      char19,
      char20,
      sep = "")
    char = gsub("=","<<-",char)
  }else if(!global){
    char =  paste(
      char1,
      char2,
      char3,
      char4,
      char5,
      char6,
      char7,
      char8,
      char9,
      char10,
      char11,
      char12,
      char13,
      char14,
      char15,
      char16,
      char17,
      char18,
      char19,
      char20,
      sep = "")
  }
  return(eval(parse(text = char)))
}